//! Embeds the guest-agent source set into the tdvmm binary, so a standalone
//! `tdvmm build` can compile the agent from source inside the pinned container
//! with no checkout and no download (owner ruling: nothing precompiled).
//!
//! Generates `$OUT_DIR/agent_src.rs` — a static `(relpath, bytes)` table over
//! EXACTLY the set `agent_src_id` hashes: the `tdvmm-agent/` + `tdvmm-proto/`
//! trees plus the root `Cargo.lock` (see `src/build/agent.rs` for the identity
//! contract and the checkout-parity tripwire test). The root `Cargo.toml` is a
//! materialize-only input embedded separately via `include_str!`.

use std::path::{Path, PathBuf};

/// The embedded source trees, repo-root-relative.
const TREES: &[&str] = &["tdvmm-agent", "tdvmm-proto"];

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let mut rels = vec!["Cargo.lock".to_string()];
    for tree in TREES {
        collect(&root, &root.join(tree), &mut rels);
    }
    // Sorted by full relpath: the identity hash in agent.rs iterates the table
    // in order and relies on it matching `tree_hash`'s sorted-relpath order.
    rels.sort();

    let mut out = String::from(
        "/// The embedded guest-agent source set (repo-root-relative path, contents),\n\
         /// generated by the root build.rs from the checkout. See [`agent_src_id`].\n\
         static AGENT_SRC: &[(&str, &[u8])] = &[\n",
    );
    for rel in &rels {
        assert!(
            rel.bytes().all(|b| b.is_ascii_alphanumeric() || b"._-/".contains(&b)),
            "embedded source path {rel:?} needs escaping the generator does not do"
        );
        out.push_str(&format!(
            "    ({rel:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel}\"))),\n"
        ));
        println!("cargo:rerun-if-changed={}", root.join(rel).display());
    }
    out.push_str("];\n");

    let dst = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("agent_src.rs");
    std::fs::write(&dst, out).expect("write agent_src.rs");
}

/// Collect every regular file under `dir` (recursively, symlinks skipped —
/// `tree_hash` parity) into `rels`, repo-root-relative with `/` separators.
fn collect(root: &Path, dir: &Path, rels: &mut Vec<String>) {
    // Watch the directory itself too, so adding/removing a source file
    // regenerates the table.
    println!("cargo:rerun-if-changed={}", dir.display());
    let entries = std::fs::read_dir(dir).unwrap_or_else(|e| panic!("{}: {e}", dir.display()));
    for entry in entries {
        let path = entry.expect("read_dir entry").path();
        let meta = std::fs::symlink_metadata(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        if meta.is_dir() {
            collect(root, &path, rels);
        } else if meta.is_file() {
            // A stale pre-pivot `agent.lock` (deleted from the repo) must never
            // perturb the embedded identity.
            if path.file_name().is_some_and(|n| n == "agent.lock") {
                continue;
            }
            let rel = path
                .strip_prefix(root)
                .expect("collected file under the manifest dir")
                .to_str()
                .unwrap_or_else(|| panic!("non-UTF-8 source path {}", path.display()))
                .to_string();
            rels.push(rel);
        }
    }
}
