//! emit-lock: transform a validated compose document into the deterministic
//! `compose.lock.yml` — the only compose file the guest sees.
//!
//! Given the resolved image digests, the in-guest bind base, and the pinned project
//! name ([`EmitLockRequest`]), [`emit_lock`] re-validates, pins every `image:` /
//! `build:` service to its `repo@sha256`, strips the host-only keys (`ports`,
//! `pull_policy`), rewrites relative binds to their in-guest paths, injects the
//! event-bridge FIFO bind into every service, and renders the result through the
//! PyYAML-faithful [emitter](super::yaml_emitter). The lock bytes are a byte-identity
//! acceptance gate, so the header and every transform are fixed.

use std::collections::HashMap;
use std::path::Path;

use serde_yaml::{Mapping, Value};

use super::error::{internal, ValidateError};
use super::validate::{build_output_tag, split_bind, validate, Bind};
use super::yaml_emitter::emit_yaml;

/// The one-line header prefixed onto every emitted `compose.lock.yml`.
pub const LOCK_HEADER: &str = "# generated by tdvmm build -- do not edit\n";

/// The guest-side event-bridge FIFO bind path (schema 3): created on the /run tmpfs
/// at boot and bind-mounted read-write into every service so workloads can write
/// assertion events the agent forwards over ttyS1. Emitted verbatim (never rewritten
/// like a relative bind); source of truth is [`tdvmm_proto::EVENT_FIFO_PATH`].
pub const EVENT_FIFO: &str = tdvmm_proto::EVENT_FIFO_PATH;

/// The inputs to [`emit_lock`]: the parsed compose `doc`, the path it was read from
/// (resolves relative binds), the resolved `digests` (an original image ref or a
/// build output tag → its pinned `repo@sha256`), the in-guest `binds_base`, and the
/// pinned `project` name.
pub struct EmitLockRequest<'a> {
    pub doc: &'a Value,
    pub compose_path: &'a Path,
    pub digests: &'a HashMap<String, String>,
    pub binds_base: &'a str,
    pub project: &'a str,
}

/// The bind copy-manifest: (host-src-abs, in-guest-relative-dest) for each bind.
type BindManifest = Vec<(String, String)>;

/// In-guest destination path for a bind, keyed by (service, mount target).
type BindDests = HashMap<(String, String), String>;

/// Result of [`emit_lock`]: the lockfile bytes and the bind copy-manifest.
pub struct LockOutput {
    pub lock_yaml: Vec<u8>,
    pub bind_manifest: BindManifest,
}

/// Transform the parsed compose `doc` into the deterministic lockfile.
///
/// # Errors
///
/// Re-runs [`validate`], so returns its [`ValidateError::Reject`] / [`ValidateError::Io`]
/// for an out-of-subset compose; returns [`ValidateError::Internal`] if a `build:`
/// output has no supplied digest or the document shape drifted from what validation
/// guaranteed.
pub fn emit_lock(req: EmitLockRequest<'_>) -> Result<LockOutput, ValidateError> {
    let EmitLockRequest { doc, compose_path, digests, binds_base, project } = req;

    // Re-validate first so a lock is never emitted for a reject.
    let validated = validate(doc, compose_path)?;
    let (bind_manifest, dest_of) = bind_dests(&validated.binds, binds_base);

    let mut doc = doc.clone();
    let m = doc.as_mapping_mut().ok_or_else(|| internal("top level is not a mapping"))?;
    m.insert(Value::String("name".into()), Value::String(project.to_string()));

    let services = m
        .get_mut(Value::String("services".into()))
        .and_then(|v| v.as_mapping_mut())
        .ok_or_else(|| internal("services missing"))?;

    // Iterate services in document order (matches Python dict iteration).
    let snames: Vec<String> = services.keys().filter_map(|k| k.as_str().map(String::from)).collect();
    for sname in snames {
        let scfg = services
            .get_mut(Value::String(sname.clone()))
            .and_then(|v| v.as_mapping_mut())
            .ok_or_else(|| internal(format!("service '{sname}' not a mapping")))?;

        pin_service_image(&sname, scfg, digests)?;
        scfg.remove(Value::String("ports".into()));
        scfg.remove(Value::String("pull_policy".into()));
        let newvols = rewrite_volumes(&sname, scfg, &dest_of);
        scfg.insert(Value::String("volumes".into()), Value::Sequence(newvols));
    }

    let mut lock_yaml = LOCK_HEADER.as_bytes().to_vec();
    lock_yaml.extend_from_slice(&emit_yaml(&doc));

    Ok(LockOutput { lock_yaml, bind_manifest })
}

/// Build the bind copy-manifest and the per-(service, target) in-guest destination
/// map from the validated relative binds.
fn bind_dests(binds: &[Bind], binds_base: &str) -> (BindManifest, BindDests) {
    let mut bind_manifest = Vec::new();
    let mut dest_of: BindDests = HashMap::new();
    for b in binds {
        let dest = format!("{}/{}/{}", binds_base, b.service, b.basename);
        dest_of.insert((b.service.clone(), b.target.clone()), dest.clone());
        bind_manifest.push((b.src.clone(), format!("{}/{}", b.service, b.basename)));
    }
    (bind_manifest, dest_of)
}

/// Pin a service to its `repo@sha256`: replace a `build:` with the `image:` its output
/// tag baked to, or pin an existing `image:` if a digest was supplied for it.
fn pin_service_image(
    sname: &str,
    scfg: &mut Mapping,
    digests: &HashMap<String, String>,
) -> Result<(), ValidateError> {
    if scfg.contains_key(Value::String("build".into())) {
        let tag = build_output_tag(sname, scfg);
        scfg.remove(Value::String("build".into()));
        match digests.get(&tag) {
            Some(pin) => {
                scfg.insert(Value::String("image".into()), Value::String(pin.clone()));
            }
            None => {
                return Err(internal(format!(
                    "service '{sname}' build output '{tag}' was not baked/pinned \
                     (no digest supplied to emit-lock)."
                )));
            }
        }
    } else if let Some(img) = scfg.get(Value::String("image".into())).and_then(|v| v.as_str()).map(String::from) {
        if let Some(pin) = digests.get(&img) {
            scfg.insert(Value::String("image".into()), Value::String(pin.clone()));
        }
    }
    Ok(())
}

/// Rewrite a service's relative binds (ro OR rw) to in-guest absolute paths, then
/// append the event-bridge FIFO bind (schema 3) so every workload can write assertion
/// events the agent forwards over ttyS1. The FIFO file is created on the guest /run
/// tmpfs at boot; binding the FILE (not the dir) means no container can unlink or
/// replace the shared inode. Its absolute path is emitted verbatim.
fn rewrite_volumes(sname: &str, scfg: &Mapping, dest_of: &BindDests) -> Vec<Value> {
    let existing = match scfg.get(Value::String("volumes".into())).cloned() {
        Some(Value::Sequence(vols)) => vols,
        _ => Vec::new(),
    };
    let mut newvols: Vec<Value> = Vec::new();
    for entry in &existing {
        if let Some((src, target, mode)) = split_bind(entry) {
            if !(src.starts_with('/') || src.starts_with('~')) {
                if let Some(dest) = dest_of.get(&(sname.to_string(), target.clone())) {
                    let norm_mode = if mode.split(',').any(|x| x == "ro") { "ro" } else { "rw" };
                    newvols.push(Value::String(format!("{dest}:{target}:{norm_mode}")));
                    continue;
                }
            }
        }
        newvols.push(entry.clone());
    }
    newvols.push(Value::String(format!("{EVENT_FIFO}:{EVENT_FIFO}:rw")));
    newvols
}
