# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orders_pb2 as orders__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in orders_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderServiceStub(object):
    """The order-ingest + stats service the client drives once per virtual hour.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrders = channel.unary_unary(
                '/demo.OrderService/SubmitOrders',
                request_serializer=orders__pb2.OrderBatch.SerializeToString,
                response_deserializer=orders__pb2.SubmitAck.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/demo.OrderService/GetStats',
                request_serializer=orders__pb2.StatsRequest.SerializeToString,
                response_deserializer=orders__pb2.StatsReply.FromString,
                _registered_method=True)


class OrderServiceServicer(object):
    """The order-ingest + stats service the client drives once per virtual hour.
    """

    def SubmitOrders(self, request, context):
        """Ingest a batch of orders for a given virtual hour: writes them to Postgres
        and bumps the Redis "orders ever received" counter, atomically-ish.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Read-side: current order count (Postgres) + cached total (Redis).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrders,
                    request_deserializer=orders__pb2.OrderBatch.FromString,
                    response_serializer=orders__pb2.SubmitAck.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=orders__pb2.StatsRequest.FromString,
                    response_serializer=orders__pb2.StatsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.OrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.OrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderService(object):
    """The order-ingest + stats service the client drives once per virtual hour.
    """

    @staticmethod
    def SubmitOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.OrderService/SubmitOrders',
            orders__pb2.OrderBatch.SerializeToString,
            orders__pb2.SubmitAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.OrderService/GetStats',
            orders__pb2.StatsRequest.SerializeToString,
            orders__pb2.StatsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
