# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x04\x64\x65mo\")\n\nOrderBatch\x12\x0c\n\x04hour\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"2\n\tSubmitAck\x12\x10\n\x08received\x18\x01 \x01(\x05\x12\x13\n\x0bredis_total\x18\x02 \x01(\x03\"\x0e\n\x0cStatsRequest\"L\n\nStatsReply\x12\x13\n\x0border_count\x18\x01 \x01(\x03\x12\x13\n\x0b\x63\x61\x63he_total\x18\x02 \x01(\x03\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x03\x32s\n\x0cOrderService\x12\x31\n\x0cSubmitOrders\x12\x10.demo.OrderBatch\x1a\x0f.demo.SubmitAck\x12\x30\n\x08GetStats\x12\x12.demo.StatsRequest\x1a\x10.demo.StatsReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERBATCH']._serialized_start=22
  _globals['_ORDERBATCH']._serialized_end=63
  _globals['_SUBMITACK']._serialized_start=65
  _globals['_SUBMITACK']._serialized_end=115
  _globals['_STATSREQUEST']._serialized_start=117
  _globals['_STATSREQUEST']._serialized_end=131
  _globals['_STATSREPLY']._serialized_start=133
  _globals['_STATSREPLY']._serialized_end=209
  _globals['_ORDERSERVICE']._serialized_start=211
  _globals['_ORDERSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
